package ch.hedgesphere

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                // FIXME hack to turn off security for the moment
                return true

                // Access control by convention.
                accessControl()
            }
            after = {
                response.setHeader('Strict-Transport-Security', 'max-age=8640000; includeSubDomains')
            }
        }
    }
}
