package ch.hedgesphere

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Access control by convention - all resources are protected, even static ones
                accessControl()
            }
            after = {
                // enforce secure transport when we are using HTTPS
                if(request.getScheme().equals("https")) {
                    response.setHeader('Strict-Transport-Security', 'max-age=8640000; includeSubDomains')
                }
            }
        }
    }
}
